//! The `LicenseGrant` record identifier (`tdd.phase-1` §6.1, §6.2): a
//! monotonic UUIDv7 per the map's record-identifier decision (ticket #8).
//!
//! Pure value wrapper only. Generation is deliberately not here:
//! `Uuid::now_v7()` reads `SystemTime` + OS entropy, which would soften
//! "Domain modules perform no I/O" (`backend_arch_docs/dependency-rules.md`);
//! the application layer generates IDs in `crate::application::id` (follow-up
//! Xaidel/brs#21 decision).

use std::fmt;

use uuid::Uuid;

/// The `LicenseGrant` record identifier: a monotonic UUIDv7 (`tdd.phase-1`
/// §6.2). Generated by the application layer (`crate::application::id`), never
/// by the domain.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct LicenseGrantId(Uuid);

impl LicenseGrantId {
    /// Wraps an existing UUID.
    pub const fn from_uuid(uuid: Uuid) -> Self {
        Self(uuid)
    }

    /// The underlying UUID.
    pub const fn as_uuid(&self) -> Uuid {
        self.0
    }
}

impl fmt::Display for LicenseGrantId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}
